# Generated by Django 2.2.3 on 2019-09-11 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20190911_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='car',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main_app.Car'),
            preserve_default=False,
        ),
    ]
