# Generated by Django 2.2.3 on 2019-09-11 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_maintenance_car'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenance',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='maintenance',
            name='cost',
            field=models.IntegerField(default=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maintenance',
            name='details',
            field=models.CharField(default='Looks good', max_length=200),
            preserve_default=False,
        ),
    ]
